# Generated by Django 5.1.1 on 2024-09-16 14:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_forum_forummodel_rename_message_messagemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forummodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forummodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='forummodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
